name: Semgrep

on:
  pull_request: {}
  push:
    branches:
      - main
      - staging
      - preview

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Run Semgrep
        id: semgrep
        continue-on-error: true
        run: |
          semgrep scan \
            --config apps/secure-semgrep/rules \
            --config p/default \
            --config p/security-audit \
            --sarif \
            --output=semgrep.sarif

      - name: Upload SARIF
        # if fork PR, don't upload their SARIF
        if: steps.semgrep.outcome == 'success' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        uses: github/codeql-action/upload-sarif@9fddc16f0de775b9edd8a84dd5839ac2db070f8b
        with:
          sarif_file: semgrep.sarif
